---
ID: "eea65ba3-31ce-4e94-9528-8303c8ef2b9e"
Parent: "ed7f41f7-4e48-41f7-bc49-cfb409e55346"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: /sitecore/content/sugconindia/sugconindia/Presentation/Placeholder Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230822T092700Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Mohd Kashif
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Mohd Kashif
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f6746384-897b-42e2-aa9e-862f95722360"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Mohd Kashif
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230822T092700Z
