---
ID: "8f944e34-7db5-438a-9751-f927d1ef6c5f"
Parent: "9f5e0c1e-7489-4fbf-8460-1e83cc178b24"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/content/sugconindia/sugconindia/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230822T092659Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Mohd Kashif
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Mohd Kashif
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "902ac471-1f7d-4064-ac7d-6936156850c0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Mohd Kashif
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230822T092659Z
